name: Latest blog post workflow
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repos README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "4"
          feed_list: "[![Latest blog post workflow](https://github.com/Googluu/GlooGluu/actions/workflows/blog-post-workflow.yml/badge.svg)](https://github.com/Googluu/GlooGluu/actions/workflows/blog-post-workflow.yml)"
